FROM mcr.microsoft.com/dotnet/sdk:8.0
RUN apt-get update && apt-get install -y --no-install-recommends \
    libheif1 \
    libde265-0 \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN dotnet restore MattLab.Chat.slnx
EXPOSE 5000
CMD ["dotnet", "watch", "--project", "src/API/LittleChat.API", "run", "--no-hot-reload"]
